### ISSUE TITLE
DQN_HRL object has no attribute 'num_input_extra'

### ISSUE THREAD

**Issue by praj441** [liruiw/HCG#2]
Its seems to be a bug in the file HCG/core/agent.py , line 33:
self.num_inputs = num_inputs + self.num_input_extra

the variable self.num_input_extra is not defined. Please clarify.

**Comment by praj441** [comment]
Again, in a similar way, I am getting error:
HCG/core/utils.py, line 1165
DQN_HRL object has no attribute 'extra_pred_dim'

**Comment by praj441** [comment]
I got a workaround to this problem.  I called the following function in the file HCG/experiments/config.py, at the end:
process_cfg()

But, Now getting the runtime error. The error logs are as follow:

==== loaded scene: scene_1 target: 021_bleach_cleanser idx: 8
Traceback (most recent call last):
  File "/home/prem/anaconda3/envs/prem3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/prem/anaconda3/envs/prem3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/prem/prem_workspace/HCG/HCG/core/test_offline.py", line 413, in <module>
    test(run_iter=run_iter)
  File "/home/prem/prem_workspace/HCG/HCG/core/test_offline.py", line 281, in test
    gt_traj=input_exec_traj)
  File "/home/prem/anaconda3/envs/prem3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/prem/prem_workspace/HCG/HCG/core/agent.py", line 190, in select_action
    actions = self.policy.sample(feature)
  File "/home/prem/prem_workspace/HCG/HCG/core/network_arch.py", line 223, in sample
    mean, log_std, extra_pred = self.forward(state)
  File "/home/prem/prem_workspace/HCG/HCG/core/network_arch.py", line 208, in forward
    x = F.relu(self.linear1(state))
  File "/home/prem/anaconda3/envs/prem3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/prem/anaconda3/envs/prem3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/prem/anaconda3/envs/prem3/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
**RuntimeError: size mismatch, m1: [1 x 513], m2: [577 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290**

**Comment by liruiw** [comment]
Could you show me which commands you are running? I think the size mismatch is due to no plan latent is provided (64 dim). Could you try the demo scripts and see if those work.

**Comment by praj441** [comment]
Hi,
Thanks for the response.

I am running the demo script itself as advised --> bash experiments/scripts/test_demo.sh

Yes, I am able to guess that the problem is due to no plan latent being provided. But I don't know why it's happening. I didn't do any other modification and just followed the steps given.

**Comment by liruiw** [comment]
I think maybe the config file has some issues based on this and your first post. Could you try re-downloading the model files and double-check pyyaml==3.12.

**Comment by praj441** [comment]
Okay, it's working now.  The problem was that the model files were not properly downloaded previously using the script. I downloaded and extracted them manually. Now the demo code is working correctly without any modification to the code. Even I don't need to call the process_cfg() function explicitly as mentioned in my earlier comment.  

My pyyaml version is 5.2, still no issue.

Thanks for your great reply and your patience !! :)

**Comment by praj441** [comment]
Hi,

Unfortunately, I got the same size mismatch error while testing. My pyyaml version is also set to now to 3.12 as suggested.

**command** - bash experiments/scripts/test_ycb.sh demo_model_clutter

**here are the logs:-**
+ echo Logging output to output/demo_model_clutter/test_log.txt.2022-04-27_20-45-45
Logging output to output/demo_model_clutter/test_log.txt.2022-04-27_20-45-45
++ basename experiments/scripts/test_ycb.sh
+ python -m core.test_offline --pretrained output/demo_model_clutter --test --record --log --load_test_scene --egl --load_goal --test_script_name test_ycb.sh --test_episode_num 300 --num_runs 2 --model_surfix latest
pybullet build time: Apr 26 2022 03:11:02
This module depends on PyOpenGL.
Please run "[1m!pip install -q pyopengl[0m" prior importing this module.
Let's use 3 GPUs!
net_name: traj_feature_extractor
=== net option: 4 trainable param: [975232, 139840]  === 
schedule: [20000, 40000, 60000, 80000, 100000]
net_name: traj_feature_sampler
=== net option: 2 trainable param: [352800, 527360]  === 
schedule: [20000, 40000, 60000, 80000, 100000]
net_name: state_feature_extractor
=== net option: 2 trainable param: [352768, 527360]  === 
=== net option: 2 trainable param: [352768, 527360]  === 
schedule: [20000, 40000, 60000, 80000, 100000]
output_time: demo_model_clutter logdir: output/demo_model_clutter/PandaYCBEnv_DQN_HRL
video output: YCB_dqn_0w_16g_gaddpg_ycb_mix stat output: rollout_success.script_dqn_0w_16g_gaddpg_ycb_mix.yaml.txt
DEBUG: 1 1024
DEBUG: 1089 256
DEBUG: 1089 256
load policy weight: 1.460 from output/demo_model_clutter/DQN_HRL_actor_PandaYCBEnv_latest !!!!
load critic weight: 0.500 !!!!
load traj feature weight: 1.203 from output/demo_model_clutter/DQN_HRL_traj_feat_PandaYCBEnv_latest !!!!
load traj sampler weight: 1.156 from output/demo_model_clutter/DQN_HRL_traj_sampler_PandaYCBEnv_latest !!!!
load feature weight: 1.6373310089111328 !!!! from: output/demo_model_clutter/DQN_HRL_state_feat_PandaYCBEnv_latest step :220001
Let's use 3 GPUs!
net_name: state_feature_extractor
=== net option: 0 trainable param: [345152, 1053184]  === 
=== net option: 0 trainable param: [345536, 1053184]  === 
schedule: [8000, 16000, 30000, 50000, 70000, 90000]
DEBUG: 1 512
DEBUG: 513 256
DEBUG: 513 256
load policy weight: 0.863 from output/demo_model/DDPG_actor_PandaYCBEnv_latest !!!!
load critic weight: 0.439 !!!!
load feature weight: 12.371764183044434 !!!! from: output/demo_model/DDPG_state_feat_PandaYCBEnv_latest step :249921
start test time: 27_04_2022_20:45:56
==== loaded scene: scene_1 target: 021_bleach_cleanser idx: 8
Traceback (most recent call last):
  File "/home/prem/anaconda3/envs/antipodal/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/prem/anaconda3/envs/antipodal/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/prem/prem_workspace/HCG/HCG/core/test_offline.py", line 413, in <module>
    test(run_iter=run_iter)
  File "/home/prem/prem_workspace/HCG/HCG/core/test_offline.py", line 281, in test
    gt_traj=input_exec_traj)
  File "/home/prem/anaconda3/envs/antipodal/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/prem/prem_workspace/HCG/HCG/core/agent.py", line 190, in select_action
    actions = self.policy.sample(feature)
  File "/home/prem/prem_workspace/HCG/HCG/core/network_arch.py", line 223, in sample
    mean, log_std, extra_pred = self.forward(state)
  File "/home/prem/prem_workspace/HCG/HCG/core/network_arch.py", line 208, in forward
    x = F.relu(self.linear1(state))
  File "/home/prem/anaconda3/envs/antipodal/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/prem/anaconda3/envs/antipodal/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/prem/anaconda3/envs/antipodal/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
**RuntimeError: size mismatch, m1: [1 x 1025], m2: [1089 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290**

**Comment by liruiw** [comment]
Could you try using only one GPU and see if that works? Sorry the test code assumes that only one GPU is used. Also does the script work previously when you load the correct model and config?

**Comment by praj441** [comment]
Hi,

I tried running with one GPU, still getting the same error. Yes, the demo script worked previously. But, this test script is not working now.

**Comment by liruiw** [comment]
The test_ycb.py is for testing the low-level policy, so it should be encoding the [expert ](https://github.com/liruiw/HCG/blob/master/core/test_offline.py#L270)plan as the plan latent for the low-level policy. Could you check if the [plan latent ](https://github.com/liruiw/HCG/blob/master/core/traj.py#L134)has been encoded.

**Comment by praj441** [comment]
@liruiw 
Thanks for guiding the error cause. 
The issue was that in file core/utils.py, line 43 - "from OMG.ycb_render.robotPose import robot_pykdl"
Because this line is within a try clause, the error was not detected earlier. 
During OMG installation, the kdl module didn't installed properly. I reinstalled it correctly and everything is working properly now.
