### ISSUE TITLE
Regarding the training script?

### ISSUE THREAD

**Issue by praj441** [liruiw/HCG#3]
Hi,

I have a doubt regarding running the training script. I have run the script for training the latent plan embedding and low-level policy as follows:
bash ./experiments/scripts/train_embedding_ray_offline.sh bc_embedding_low_level.yaml BC

It is running for 2 days but I am not able to understand how to visualize its progress, error grasps, etc. On the terminal, nothing is updated since I run the script (I am attaching the screenshot ![hcg](https://user-images.githubusercontent.com/28840137/166105062-8443372c-80a5-46f6-ad94-f0550144ee09.png)). 

Also, its GPU uses is very less, mostly its using CPU?

**Comment by liruiw** [comment]
This is very strange. Typically the program hangs can be due to ray is waiting, so you could check more on lines like this [one](https://github.com/liruiw/HCG/blob/master/core/train_offline.py#L234). The offline training can also be done without ray.

**Comment by praj441** [comment]
Okay, I will check this one.

Before that, I wanna ask whether is it necessary to maintain the two separate conda envs for training and demo as suggested in the ReadMe. Currently, I am using the one single conda env for both of them. Could this be a problem?

**Comment by liruiw** [comment]
No you could just use the one with the OMG planner. Sorry for the confusion.
