### ISSUE TITLE
mismatch between pretrained model and current model

### ISSUE THREAD

**Issue by matt60110552** [liruiw/HCG#4]
Hi, I found a error when I tried to reproduce your HCG repo, it said that something was wrong when I tried to load a pretrained model.

This is what I encountered when I execute **bash experiments/scripts/test_demo.sh**
![hcg](https://user-images.githubusercontent.com/94676000/207844633-7b10fff5-f898-4774-9c5d-b67fc95e9fc9.png)

My environment : 
ubuntu20.04, 
cuda 11.3, 
torch==1.10.2+cu113, 
torchaudio==0.10.2+cu113,
torchfile==0.1.0,
torchvision==0.11.3+cu113.

**Comment by liruiw** [comment]
I don't seem to have this issue though. I also has similar setup but I did not use docker. Could you try redownloading the model checkpoints?
